version: "3.5"
services:
  nps_server_app:
    container_name: nps_server
    volumes:
      - ./nps/conf:/conf
    build: ./nps

  nginx_app:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/logs:/var/nginx/logs
    ports:
      - "80:80"
      # bridge port in ../nps/conf/nps.conf
      - "8024:8024"
      - "8080:8080"
      - "8081:8081"
      # web port in ../nps/conf/nps.conf
      - "9090:9090"
